### ISSUE TITLE
Propose download of Kamel excutable if not available

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camelk#105] opened 2019-09-05 08:29 UTC
"We will then just have to find a way to pull in the Camel K executable like they pull in their executables to ensure that they're available."

even more important if going with Kamel only way of doing see #104

**Comment by bfitzpat** [comment] 2019-09-05 17:08
It's a duplicate of https://github.com/camel-tooling/vscode-camelk/issues/50

**Closed** 2019-09-06 07:06 UTC
